#!/usr/bin/env node

/**
 * Cron Job Manager for iseeiape
 * 
 * Manages automated tasks for data updates, content generation,
 * and system maintenance.
 * 
 * Usage: node scripts/cron-manager.js [action] [options]
 * 
 * Actions:
 *   setup     - Set up cron jobs
 *   run       - Run a specific job
 *   list      - List all jobs
 *   status    - Check job status
 *   test      - Test job execution
 */

const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');
const cron = require('node-cron');

// Configuration
const CONFIG = {
  jobsDir: path.join(__dirname, '../neo-crypto/cron-jobs'),
  logsDir: path.join(__dirname, '../neo-crypto/logs'),
  dataDir: path.join(__dirname, '../neo-crypto/data'),
  
  // Job definitions
  jobs: {
    'data-update': {
      schedule: '*/30 * * * *', // Every 30 minutes
      script: 'scripts/enhanced-api.js',
      description: 'Update market data and whale tracking',
      enabled: true
    },
    'content-generation': {
      schedule: '0 */6 * * *', // Every 6 hours
      script: 'scripts/auto-content-generator.js',
      description: 'Generate new insight articles',
      enabled: true,
      args: ['--topic', 'auto']
    },
    'social-media': {
      schedule: '0 */4 * * *', // Every 4 hours
      script: 'scripts/social-media-generator.js',
      description: 'Create social media posts from insights',
      enabled: false // Not implemented yet
    },
    'cleanup': {
      schedule: '0 0 * * *', // Daily at midnight
      script: 'scripts/cleanup.js',
      description: 'Clean up old logs and temporary files',
      enabled: true
    },
    'backup': {
      schedule: '0 2 * * *', // Daily at 2 AM
      script: 'scripts/backup.js',
      description: 'Backup critical data',
      enabled: true
    },
    'wolf-pack': {
      schedule: '*/15 * * * *', // Every 15 minutes
      script: 'scripts/wolf-pack-runner.js',
      description: 'Run Wolf Pack alerts and integration',
      enabled: true
    }
  }
};

// Ensure directories exist
function ensureDirectories() {
  [CONFIG.jobsDir, CONFIG.logsDir].forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(`📁 Created directory: ${dir}`);
    }
  });
}

// Create job files
function createJobFiles() {
  console.log('📝 Creating job files...');
  
  Object.entries(CONFIG.jobs).forEach(([jobName, jobConfig]) => {
    if (!jobConfig.enabled) return;
    
    const jobFile = path.join(CONFIG.jobsDir, `${jobName}.js`);
    
    const jobContent = `#!/usr/bin/env node

/**
 * ${jobConfig.description}
 * 
 * Generated by Cron Manager
 * Schedule: ${jobConfig.schedule.replace(/\*\//g, '*\\/')}
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const LOGS_DIR = path.join(__dirname, '../../neo-crypto/logs');
const JOB_NAME = '${jobName}';
const TIMESTAMP = new Date().toISOString().replace(/[:.]/g, '-');

// Ensure logs directory exists
if (!fs.existsSync(LOGS_DIR)) {
  fs.mkdirSync(LOGS_DIR, { recursive: true });
}

function log(message, level = 'INFO') {
  const logMessage = \`[\${new Date().toISOString()}] [\${level}] \${message}\\n\`;
  const logFile = path.join(LOGS_DIR, \`\${JOB_NAME}-\${TIMESTAMP}.log\`);
  
  fs.appendFileSync(logFile, logMessage);
  console.log(logMessage.trim());
}

function logError(error) {
  log(\`Error: \${error.message}\`, 'ERROR');
  if (error.stack) {
    log(\`Stack: \${error.stack}\`, 'ERROR');
  }
}

async function main() {
  log(\`Starting \${JOB_NAME} job\`);
  log(\`Schedule: ${jobConfig.schedule}\`);
  log(\`Description: ${jobConfig.description}\`);
  
  try {
    const startTime = Date.now();
    
    // Execute the main script
    const scriptPath = path.join(__dirname, '../../${jobConfig.script}');
    const args = ${JSON.stringify(jobConfig.args || [])};
    
    log(\`Executing: node \${scriptPath} \${args.join(' ')}\`);
    
    const result = execSync(
      \`node "\${scriptPath}" \${args.join(' ')}\`,
      { 
        encoding: 'utf8',
        stdio: ['pipe', 'pipe', 'pipe'],
        cwd: path.join(__dirname, '../../')
      }
    );
    
    const executionTime = Date.now() - startTime;
    
    log(\`Execution completed in \${executionTime}ms\`);
    log(\`Output: \${result.substring(0, 500)}\${result.length > 500 ? '...' : ''}\`);
    
    // Check for errors in output
    if (result.includes('❌') || result.includes('Error:') || result.includes('error:')) {
      log('Potential errors detected in output', 'WARN');
    }
    
    log(\`Job \${JOB_NAME} completed successfully\`);
    
  } catch (error) {
    logError(error);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main().catch(error => {
    logError(error);
    process.exit(1);
  });
}

module.exports = { main };
`;
    
    fs.writeFileSync(jobFile, jobContent, 'utf8');
    fs.chmodSync(jobFile, '755'); // Make executable
    
    console.log(`  ✅ Created: ${jobFile}`);
  });
  
  console.log(`\n📋 Created ${Object.values(CONFIG.jobs).filter(j => j.enabled).length} job files`);
}

// Create systemd service file (for production)
function createSystemdService() {
  const serviceContent = `[Unit]
Description=iseeiape Neo Crypto Engine Cron Manager
After=network.target

[Service]
Type=simple
User=${process.env.USER || 'matrix'}
WorkingDirectory=${path.join(__dirname, '..')}
ExecStart=/usr/bin/node ${path.join(__dirname, 'cron-manager.js')} start
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
`;
  
  const serviceFile = path.join(CONFIG.jobsDir, 'iseeiape-cron.service');
  fs.writeFileSync(serviceFile, serviceContent, 'utf8');
  
  console.log(`📋 Created systemd service: ${serviceFile}`);
  console.log('\nTo install:');
  console.log(`  sudo cp ${serviceFile} /etc/systemd/system/`);
  console.log('  sudo systemctl daemon-reload');
  console.log('  sudo systemctl enable iseeiape-cron');
  console.log('  sudo systemctl start iseeiape-cron');
}

// Create PM2 ecosystem file (alternative)
function createPm2Ecosystem() {
  const ecosystemContent = `module.exports = {
  apps: [
    {
      name: 'iseeiape-cron',
      script: '${path.join(__dirname, 'cron-manager.js')}',
      args: 'start',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: '${path.join(CONFIG.logsDir, 'cron-error.log')}',
      out_file: '${path.join(CONFIG.logsDir, 'cron-out.log')}',
      log_file: '${path.join(CONFIG.logsDir, 'cron-combined.log')}',
      time: true
    }
  ]
};
`;
  
  const ecosystemFile = path.join(CONFIG.jobsDir, 'ecosystem.config.js');
  fs.writeFileSync(ecosystemFile, ecosystemContent, 'utf8');
  
  console.log(`📋 Created PM2 ecosystem file: ${ecosystemFile}`);
  console.log('\nTo start with PM2:');
  console.log(`  pm2 start ${ecosystemFile}`);
}

// Run a specific job
function runJob(jobName) {
  const jobConfig = CONFIG.jobs[jobName];
  
  if (!jobConfig) {
    console.error(`❌ Job not found: ${jobName}`);
    console.log('Available jobs:', Object.keys(CONFIG.jobs).join(', '));
    process.exit(1);
  }
  
  if (!jobConfig.enabled) {
    console.error(`❌ Job is disabled: ${jobName}`);
    process.exit(1);
  }
  
  console.log(`🚀 Running job: ${jobName}`);
  console.log(`📝 ${jobConfig.description}`);
  console.log(`⏰ Schedule: ${jobConfig.schedule}`);
  
  const jobFile = path.join(CONFIG.jobsDir, `${jobName}.js`);
  
  if (!fs.existsSync(jobFile)) {
    console.error(`❌ Job file not found: ${jobFile}`);
    console.log('Run "node scripts/cron-manager.js setup" first');
    process.exit(1);
  }
  
  try {
    const result = execSync(`node "${jobFile}"`, {
      encoding: 'utf8',
      stdio: 'inherit',
      cwd: path.join(__dirname, '..')
    });
    
    console.log(`✅ Job ${jobName} completed`);
    
  } catch (error) {
    console.error(`❌ Job ${jobName} failed:`, error.message);
    process.exit(1);
  }
}

// List all jobs
function listJobs() {
  console.log('📋 Cron Jobs Configuration\n');
  console.log('='.repeat(80));
  
  Object.entries(CONFIG.jobs).forEach(([jobName, jobConfig]) => {
    const status = jobConfig.enabled ? '✅ ENABLED' : '❌ DISABLED';
    console.log(`\n🔧 ${jobName}`);
    console.log(`   ${status}`);
    console.log(`   📝 ${jobConfig.description}`);
    console.log(`   ⏰ Schedule: ${jobConfig.schedule}`);
    console.log(`   📁 Script: ${jobConfig.script}`);
    
    if (jobConfig.args && jobConfig.args.length > 0) {
      console.log(`   ⚙️  Args: ${jobConfig.args.join(' ')}`);
    }
    
    const jobFile = path.join(CONFIG.jobsDir, `${jobName}.js`);
    console.log(`   📄 File: ${fs.existsSync(jobFile) ? '✅ Exists' : '❌ Missing'}`);
  });
  
  console.log('\n' + '='.repeat(80));
  console.log(`\n📊 Total jobs: ${Object.keys(CONFIG.jobs).length}`);
  console.log(`✅ Enabled: ${Object.values(CONFIG.jobs).filter(j => j.enabled).length}`);
  console.log(`❌ Disabled: ${Object.values(CONFIG.jobs).filter(j => !j.enabled).length}`);
}

// Check job status
function checkStatus() {
  console.log('📊 Cron Job Status\n');
  console.log('='.repeat(80));
  
  // Check for recent log files
  if (fs.existsSync(CONFIG.logsDir)) {
    const logs = fs.readdirSync(CONFIG.logsDir)
      .filter(file => file.endsWith('.log'))
      .sort()
      .reverse()
      .slice(0, 10);
    
    if (logs.length > 0) {
      console.log('\n📝 Recent Logs:');
      logs.forEach(logFile => {
        const stat = fs.statSync(path.join(CONFIG.logsDir, logFile));
        const size = (stat.size / 1024).toFixed(2);
        const age = Math.floor((Date.now() - stat.mtime.getTime()) / (1000 * 60 * 60));
        
        console.log(`   ${logFile} (${size}KB, ${age}h ago)`);
      });
    } else {
      console.log('\n📝 No log files found');
    }
  }
  
  // Check data freshness
  if (fs.existsSync(CONFIG.dataDir)) {
    const dataFiles = fs.readdirSync(CONFIG.dataDir)
      .filter(file => file.endsWith('.json'))
      .slice(0, 5);
    
    if (dataFiles.length > 0) {
      console.log('\n📈 Data Files:');
      dataFiles.forEach(dataFile => {
        try {
          const filePath = path.join(CONFIG.dataDir, dataFile);
          const content = fs.readFileSync(filePath, 'utf8');
          const data = JSON.parse(content);
          const stat = fs.statSync(filePath);
          
          const age = Math.floor((Date.now() - stat.mtime.getTime()) / (1000 * 60));
          const size = (stat.size / 1024).toFixed(2);
          
          let freshness = '🟢 Fresh';
          if (age > 60) freshness = '🟡 Stale';
          if (age > 120) freshness = '🔴 Old';
          
          console.log(`   ${dataFile} (${size}KB, ${age}m ago, ${freshness})`);
          
          if (data.updated_at) {
            const dataAge = Math.floor((Date.now() - new Date(data.updated_at).getTime()) / (1000 * 60));
            console.log(`     Data updated: ${dataAge}m ago`);
          }
          
        } catch (error) {
          console.log(`   ${dataFile} (Error reading)`);
        }
      });
    }
  }
  
  console.log('\n' + '='.repeat(80));
}

// Start cron scheduler
function startScheduler() {
  console.log('🚀 Starting Cron Scheduler...');
  console.log('📊 Neo Crypto Engine • Automated Task Manager\n');
  
  ensureDirectories();
  
  // Schedule jobs
  Object.entries(CONFIG.jobs).forEach(([jobName, jobConfig]) => {
    if (!jobConfig.enabled) return;
    
    const jobFile = path.join(CONFIG.jobsDir, `${jobName}.js`);
    
    if (!fs.existsSync(jobFile)) {
      console.log(`⚠️  Job file not found: ${jobFile}`);
      console.log('   Run "node scripts/cron-manager.js setup" first');
      return;
    }
    
    // Validate cron expression
    if (!cron.validate(jobConfig.schedule)) {
      console.log(`❌ Invalid cron expression for ${jobName}: ${jobConfig.schedule}`);
      return;
    }
    
    // Schedule the job
    cron.schedule(jobConfig.schedule, () => {
      const timestamp = new Date().toISOString();
      console.log(`\n⏰ [${timestamp}] Running job: ${jobName}`);
      
      try {
        const result = execSync(`node "${jobFile}"`, {
          encoding: 'utf8',
          stdio: 'pipe',
          cwd: path.join(__dirname, '..')
        });
        
        console.log(`✅ Job ${jobName} completed successfully`);
        
      } catch (error) {
        console.error(`❌ Job ${jobName} failed:`, error.message);
      }
    });
    
    console.log(`✅ Scheduled: ${jobName} (${jobConfig.schedule})`);
  });
  
  console.log('\n📋 Scheduler running. Jobs will execute according to schedule.');
  console.log('🛑 Press Ctrl+C to stop.');
  
  // Keep process alive
  process.stdin.resume();
}

// Test job execution
function testJob(jobName) {
  console.log(`🧪 Testing job: ${jobName}`);
  
  const jobConfig = CONFIG.jobs[jobName];
  if (!jobConfig) {
    console.error(`❌ Job not found: ${jobName}`);
    return;
  }
  
  console.log(`📝 Description: ${jobConfig.description}`);
  console.log(`⏰ Schedule: ${jobConfig.schedule}`);
  console.log(`📁 Script: ${jobConfig.script}`);
  
  // Test cron expression
  if (cron.validate(jobConfig.schedule)) {
    console.log(`✅ Cron expression is valid`);
    
    // Show next 5 run times
    const schedule = cron.parseExpression(jobConfig.schedule);
    console.log(`\n📅 Next 5 run times:`);
    for (let i = 0; i < 5; i++) {
      const nextDate = schedule.next();
      console.log(`   ${i + 1}. ${nextDate.toLocaleString()}`);
    }
  } else {
    console.log(`❌ Invalid cron expression`);
  }
  
  // Test script existence
  const scriptPath = path.join(__dirname, '..', jobConfig.script);
  if (fs.existsSync(scriptPath)) {
    console.log(`✅ Script file exists: ${scriptPath}`);
  } else {
    console.log(`❌ Script file not found: ${scriptPath}`);
  }
}

// Main function
async function main() {
  const args = process.argv.slice(2);
  const action = args[0] || 'help';
  
  ensureDirectories();
  
  switch (action) {
    case 'setup':
      console.log('🔧 Setting up cron jobs...\n');
      createJobFiles();
      createSystemdService();
      createPm2Ecosystem();
      console.log('\n✅ Setup complete!');
      console.log('\nNext steps:');
      console.log('1. Review job files in neo-crypto/cron-jobs/');
      console.log('2. Test jobs with: node scripts/cron-manager.js run [job-name]');
      console.log('3. Choose deployment method (systemd or PM2)');
      console.log('4. Start scheduler: node scripts/cron-manager.js start');
      break;
      
    case 'run':
      const jobToRun = args[1];
      if (!jobToRun) {
        console.error('❌ Please specify a job to run');
        console.log('Usage: node scripts/cron-manager.js run [job-name]');
        console.log('Available jobs:', Object.keys(CONFIG.jobs).join(', '));
        process.exit(1);
      }
      runJob(jobToRun);
      break;
      
    case 'list':
      listJobs();
      break;
      
    case 'status':
      checkStatus();
      break;
      
    case 'test':
      const jobToTest = args[1];
      if (!jobToTest) {
        console.error('❌ Please specify a job to test');
        console.log('Usage: node scripts/cron-manager.js test [job-name]');
        console.log('Available jobs:', Object.keys(CONFIG.jobs).join(', '));
        process.exit(1);
      }
      testJob(jobToTest);
      break;
      
    case 'start':
      startScheduler();
      break;
      
    case 'help':
    default:
      console.log('🚀 iseeiape Cron Manager');
      console.log('📊 Neo Crypto Engine • Automated Task Manager\n');
      console.log('Usage: node scripts/cron-manager.js [action] [options]\n');
      console.log('Actions:');
      console.log('  setup           Set up cron jobs and create job files');
      console.log('  run [job]       Run a specific job immediately');
      console.log('  list            List all configured jobs');
      console.log('  status          Check job status and data freshness');
      console.log('  test [job]      Test a job configuration');
      console.log('  start           Start the cron scheduler');
      console.log('  help            Show this help message\n');
      console.log('Examples:');
      console.log('  node scripts/cron-manager.js setup');
      console.log('  node scripts/cron-manager.js run data-update');
      console.log('  node scripts/cron-manager.js status');
      console.log('  node scripts/cron-manager.js start\n');
      console.log('Job Configuration:');
      console.log('  Edit CONFIG.jobs in this script to modify schedules');
      console.log('  Job files are created in neo-crypto/cron-jobs/');
      console.log('  Logs are stored in neo-crypto/logs/\n');
      break;
  }
}

// Run if called directly
if (require.main === module) {
  // Check for node-cron dependency
  try {
    require('node-cron');
  } catch (error) {
    console.error('❌ Missing dependency: node-cron');
    console.log('Install it with: npm install node-cron');
    process.exit(1);
  }
  
  main().catch(error => {
    console.error('❌ Fatal error:', error);
    process.exit(1);
  });
}

module.exports = {
  CONFIG,
  ensureDirectories,
  createJobFiles,
  runJob,
  listJobs,
  checkStatus
};