#!/usr/bin/env python3
"""
🦈 SIMPLE WHALE TRACKER
Use existing whale wallet data to create Cielo tracking config
No API keys required - uses pre-collected data
"""

import json
import os
from datetime import datetime
from pathlib import Path

def load_existing_whale_wallets() -> list:
    """Load whale wallets from existing data files"""
    wallets = []
    
    # Check for existing whale wallet files
    data_sources = [
        "/home/matrix/insider-scanner/data/WhiteWhale_wallets.txt",
        "/home/matrix/insider-scanner/data/WhiteWhale_early_buyers_20260217_1359.json",
    ]
    
    for source in data_sources:
        if os.path.exists(source):
            print(f"📂 Loading from: {source}")
            
            if source.endswith('.txt'):
                with open(source, 'r') as f:
                    lines = f.readlines()
                    for line in lines:
                        wallet = line.strip()
                        if wallet and wallet not in wallets:
                            wallets.append(wallet)
            
            elif source.endswith('.json'):
                with open(source, 'r') as f:
                    data = json.load(f)
                    # Try different possible structures
                    if isinstance(data, list):
                        for item in data:
                            if isinstance(item, dict) and 'wallet' in item:
                                wallets.append(item['wallet'])
                            elif isinstance(item, str):
                                wallets.append(item)
                    elif isinstance(data, dict):
                        # Look for wallet arrays in the dict
                        for key, value in data.items():
                            if isinstance(value, list):
                                for item in value:
                                    if isinstance(item, str) and len(item) > 30:
                                        wallets.append(item)
    
    return list(set(wallets))  # Remove duplicates

def create_cielo_config(wallets: list, max_wallets: int = 50) -> dict:
    """Create Cielo API compatible configuration"""
    # Limit to max_wallets to avoid API limits
    limited_wallets = wallets[:max_wallets]
    
    config = {
        "name": "Auto-generated Whale Tracker",
        "description": f"Generated by Neo Night Shift on {datetime.now().isoformat()}",
        "wallets": limited_wallets,
        "chains": ["solana"],
        "alert_types": ["large_transfer", "token_buy", "token_sell"],
        "telegram_chat_id": "120001865",  # Dan's chat ID from memory
        "update_frequency": "5m",  # Check every 5 minutes
        "min_transaction_value_usd": 1000,  # Only alert on $1k+ transactions
    }
    
    return config

def create_python_tracker_script(wallets: list, max_wallets: int = 30) -> str:
    """Create a Python script for tracking wallets with Cielo API"""
    script = '''#!/usr/bin/env python3
"""
🦈 CIELO WHALE TRACKER
Auto-generated tracking script for whale wallets
"""

import requests
import json
import time
from datetime import datetime
import os

# Cielo API Configuration
CIELO_API_KEY = os.environ.get("CIELO_API_KEY", "e7a2bb7b-73f0-4362-bf3f-7b9e276f9695")
CIELO_BASE_URL = "https://feed-api.cielo.finance/api/v1"

# Telegram Configuration
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN")
TELEGRAM_CHAT_ID = "120001865"  # Dan's chat ID

# Whale wallets to track
WHALE_WALLETS = [
'''
    
    # Add wallets (limited to max_wallets)
    for i, wallet in enumerate(wallets[:max_wallets]):
        script += f'    "{wallet}",  # Whale {i+1}\n'
    
    script += ''']

def send_telegram_alert(message: str):
    """Send alert to Telegram"""
    try:
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": TELEGRAM_CHAT_ID,
            "text": message,
            "parse_mode": "HTML"
        }
        resp = requests.post(url, json=payload, timeout=10)
        return resp.status_code == 200
    except Exception as e:
        print(f"❌ Telegram error: {e}")
        return False

def check_wallet_transactions(wallet: str):
    """Check recent transactions for a wallet"""
    try:
        url = f"{CIELO_BASE_URL}/wallet/transactions"
        params = {
            "wallet": wallet,
            "chain": "solana",
            "limit": 10
        }
        headers = {
            "Authorization": f"Bearer {CIELO_API_KEY}"
        }
        
        resp = requests.get(url, params=params, headers=headers, timeout=30)
        
        if resp.status_code == 200:
            data = resp.json()
            transactions = data.get('data', [])
            
            if transactions:
                # Check for large transactions
                for tx in transactions[:5]:  # Only check most recent 5
                    value_usd = tx.get('value_usd', 0)
                    if value_usd > 1000:  # $1k threshold
                        token = tx.get('token_symbol', 'Unknown')
                        amount = tx.get('amount', 0)
                        tx_type = tx.get('type', 'transfer')
                        
                        alert_msg = f"""
🚨 WHALE ALERT 🚨

Wallet: {wallet[:10]}...{wallet[-6:]}
Action: {tx_type.upper()}
Token: {token}
Amount: ${value_usd:,.2f}
Details: {amount:,.2f} {token}

Time: {datetime.now().strftime('%H:%M:%S')}
                        """
                        
                        print(f"⚠️  Large transaction detected: ${value_usd:,.2f}")
                        send_telegram_alert(alert_msg)
            
            return len(transactions)
        else:
            print(f"❌ Cielo API error for {wallet[:10]}...: {resp.status_code}")
            return 0
    except Exception as e:
        print(f"❌ Error checking {wallet[:10]}...: {e}")
        return 0

def main():
    """Main tracking loop"""
    print("="*60)
    print("🦈 CIELO WHALE TRACKER")
    print(f"Tracking {len(WHALE_WALLETS)} whale wallets")
    print("="*60)
    
    iteration = 0
    while True:
        iteration += 1
        print(f"\n📊 Iteration {iteration} - {datetime.now().strftime('%H:%M:%S')}")
        
        total_transactions = 0
        for i, wallet in enumerate(WHALE_WALLETS, 1):
            print(f"  Checking wallet {i}/{len(WHALE_WALLETS)}...")
            tx_count = check_wallet_transactions(wallet)
            total_transactions += tx_count
            
            # Be nice to the API
            time.sleep(0.5)
        
        print(f"✅ Checked {len(WHALE_WALLETS)} wallets, found {total_transactions} recent transactions")
        print(f"⏰ Next check in 5 minutes...")
        time.sleep(300)  # 5 minutes

if __name__ == "__main__":
    main()
'''
    
    return script

def main():
    """Main execution"""
    print("="*60)
    print("🦈 SIMPLE WHALE TRACKER")
    print("Generating Cielo tracking configuration from existing data")
    print("="*60)
    
    # Load existing whale wallets
    wallets = load_existing_whale_wallets()
    
    if not wallets:
        print("❌ No whale wallet data found!")
        print("Please run the insider scanner first or add wallet data manually.")
        return
    
    print(f"✅ Loaded {len(wallets)} unique whale wallets")
    
    # Create outputs directory
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    
    # 1. Save wallet list
    wallets_file = output_dir / f"whale_wallets_{timestamp}.txt"
    with open(wallets_file, 'w') as f:
        for wallet in wallets:
            f.write(f"{wallet}\n")
    
    print(f"📁 Wallet list saved to: {wallets_file}")
    
    # 2. Create Cielo config
    config = create_cielo_config(wallets)
    config_file = output_dir / f"cielo_config_{timestamp}.json"
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)
    
    print(f"⚙️  Cielo config saved to: {config_file}")
    
    # 3. Create Python tracker script
    tracker_script = create_python_tracker_script(wallets)
    script_file = output_dir / f"cielo_whale_tracker_{timestamp}.py"
    with open(script_file, 'w') as f:
        f.write(tracker_script)
    
    # Make it executable
    os.chmod(script_file, 0o755)
    
    print(f"🐍 Tracker script saved to: {script_file}")
    
    # 4. Create README
    readme = f"""# 🦈 Whale Tracker Configuration

Generated: {datetime.now().isoformat()}

## Summary
- **Total wallets loaded:** {len(wallets)}
- **Wallets in tracker:** {min(30, len(wallets))} (limited for API performance)
- **Chain:** Solana
- **Alert threshold:** $1,000+ transactions

## Files Generated

1. `{wallets_file.name}` - List of all whale wallet addresses
2. `{config_file.name}` - Cielo API configuration
3. `{script_file.name}` - Python script for 24/7 tracking

## How to Use

### Option 1: Use with existing Insider Scanner
```bash
# Copy wallets to insider scanner
cp {wallets_file.name} ~/insider-scanner/data/whale_wallets.txt

# Update the live_cielo_dashboard.py with these wallets
```

### Option 2: Run the Python tracker directly
```bash
# Set API keys
export CIELO_API_KEY="e7a2bb7b-73f0-4362-bf3f-7b9e276f9695"
export TELEGRAM_BOT_TOKEN="your_bot_token"

# Run the tracker
python3 {script_file.name}
```

### Option 3: Add to cron for 24/7 monitoring
```bash
# Add to crontab (runs every 5 minutes)
*/5 * * * * cd /path/to/this/directory && python3 {script_file.name} >> tracker.log 2>&1
```

## Next Steps

1. **Test with a few wallets first** before tracking all
2. **Monitor Telegram alerts** to ensure they're working
3. **Adjust thresholds** based on alert volume
4. **Add more wallets** from other trending tokens

## Wallet Sources
- WhiteWhale token early buyers
- Existing insider scanner data
- Manually curated whale addresses

---
*Generated by Neo Night Shift - Building the Matrix Army 🦎*
"""
    
    readme_file = output_dir / f"README_{timestamp}.md"
    with open(readme_file, 'w') as f:
        f.write(readme)
    
    print(f"📖 README saved to: {readme_file}")
    
    print("\n" + "="*60)
    print("✅ Whale Tracker Configuration Complete!")
    print("="*60)
    print(f"\n🎯 Next steps:")
    print(f"1. Review the generated files in: {output_dir}/")
    print(f"2. Test the tracker with: python3 {script_file}")
    print(f"3. Add to cron for 24/7 monitoring")
    print(f"4. Check Telegram for alerts (Chat ID: 120001865)")

if __name__ == "__main__":
    main()